URIReference ::= [ absoluteURI | relativeURI ] [ "#" fragment ]
absoluteURI  ::= scheme ":" ( hier_part | opaque_part )
relativeURI  ::= ( net_path | abs_path | rel_path ) [ "?" query ]
hier_part    ::= ( net_path | abs_path ) [ "?" query ]
opaque_part  ::= uric_no_slash *uric

uric_no_slash ::= unreserved
                | escaped
                | "\;"
                | "?"
                | ":"
                | "@"
                | "&"
                | "="
                | "+"
                | "$"
                | ","

net_path ::= "//" authority [ abs_path ]
scheme   ::= alpha *( alpha | digit | "+" | "-" | "." )

reg_name ::= 1*(   unreserved
                 | escaped
                 | "$"
                 | ","
                 | "\;"
                 | ":"
                 | "@"
                 | "&"
                 | "="
                 | "+"
               )

server ::= [ [ userinfo "@" ] hostport ]
