# TypeProf 0.21.3

# Classes
module Yaparc
  VERSION: String

  module Result
    class Base
      attr_accessor message: nil
      attr_accessor input: nil
      attr_accessor value: nil
      def initialize: (?Hash[untyped, untyped] options) -> void
    end

    class OK < Base
    end

    class Fail < Base
    end

    class Error < Base
    end
  end

  module Parsable
    IS_LOWER: Proc
    IS_ALPHANUM: Proc
    IS_DIGIT: Proc
    IS_SPACE: Proc
    IS_WHITESPACE: Proc
    IS_CR: Proc
    @parser: bot

    attr_accessor tree: untyped
    def parse: (nil input) -> untyped
  end

  class Succeed
    include Parsable
    @parser: Proc

    attr_reader remaining: nil
    def initialize: (untyped value, ?nil remaining) -> void
  end

  class Fail
    include Parsable
    @parser: Proc

    def initialize: -> void
  end

  class Item
    include Parsable
    @parser: Proc

    def initialize: -> void
  end

  class ZeroOne
    include Parsable
    @parser: Proc

    def initialize: (untyped parser, ?Array[untyped] identity) -> void
  end

  class Satisfy
    include Parsable
    @parser: Proc

    def initialize: (Proc predicate) -> void
    def parse: (untyped input) -> untyped
  end

  class NoFail
    include Parsable
    @parser: Proc

    def initialize: (untyped parser) -> void
  end

  class Seq
    include Parsable
    @parser: Proc

    def initialize: (*Char | String | Succeed | WhiteSpace parsers) ?{ (*untyped) -> untyped } -> void
  end

  class Alt
    include Parsable
    @parser: Proc

    def initialize: (*untyped parsers) -> void
  end

  class Apply
    include Parsable
    @parser: Proc

    def initialize: (untyped parser) -> void
  end

  class String
    include Parsable
    @parser: Proc

    def initialize: (untyped string, ?true case_sensitive) -> void
  end

  class Regex
    include Parsable
    @regex: Regexp
    @parser: Proc

    def initialize: (Regexp regex) -> void
  end

  class Many
    include Parsable

    def initialize: (Satisfy parser, ?Array[untyped] | String identity) -> void
  end

  class ManyOne
    include Parsable

    def initialize: (Digit parser, ?Array[untyped] | String identity) -> void
  end

  class Space
    include Parsable
    @parser: Proc

    def initialize: -> void
  end

  class CR
    include Parsable
    @parser: Proc

    def initialize: -> void
  end

  class WhiteSpace
    include Parsable
    @parser: Proc

    def initialize: -> void
  end

  class Tokenize
    include Parsable
    @parser: Proc

    attr_accessor prefix: WhiteSpace
    attr_accessor postfix: WhiteSpace
    def initialize: (Regex | String parser, ?Hash[untyped, untyped] args) -> void
  end

  class Literal
    include Parsable
    @parser: Proc

    def initialize: (untyped literal, ?true case_sensitive) -> void
  end

  class Identifier
    IDENTIFIER_REGEX: Regexp
    include Parsable
    @parser: Proc

    def initialize: (?Hash[untyped, untyped] options) -> void
  end

  class Char
    include Parsable
    @parser: Proc

    def initialize: (untyped char, ?true case_sensitive) -> void
  end

  class Ident
    include Parsable

    def initialize: -> void
  end

  class Digit
    include Parsable
    @parser: Proc

    def initialize: -> void
  end

  class Nat
    include Parsable

    def initialize: -> void
  end

  class Natural
    include Parsable

    def initialize: (?Hash[untyped, untyped] args) -> void
  end

  class Symbol
    include Parsable
    @parser: Proc

    def initialize: (untyped literal, ?Hash[untyped, untyped] _args) -> void
  end

  class AbstractParser
    include Parsable
    @parser: bot

    def parse: (untyped input) -> untyped
  end
end
